upbit :
  key :
    AccessKey :
    SecretKey :
  address:
    market: https://api.upbit.com/v1/market/all?isDetails=false
    minuteCandle: https://api.upbit.com/v1/candles/minutes
    orderbook: https://api.upbit.com/v1/orderbook
    accounts: https://api.upbit.com/v1/accounts


spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?autoReconnect=true
      username: root
      password: 1234
      driver-class-name: com.mysql.jdbc.Driver

---




